version: '3'

services:
  meter:
    container_name: meter
    build:
      context: ./
      dockerfile: ./dockerfile
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
    network_mode: bridge
    dns: 192.168.1.30
    environment:
      - DB_TYPE=influxdb
      - DB_HOSTNAME=192.168.1.30
      - DB_PORT=8086
      - DB_USERNAME=""
      - DB_PASSWORD=""
      - DB_DATABASE=home
      - CURRENT_DATA_INTERVAL_SECONDS=30
      - TOTAL_DATA_INTERVAL_SECONDS=300
