# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      env:
        DOCKER_USERNAME: wisepotato
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE
        docker-compose build
        docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        docker push wisepotato/meter:latest